title: Hierarchical Event Descriptor (HED) Documentation
description: Guides, tutorials, help
google_analytics: UA-46460712-3
show_downloads: false
theme: jekyll-theme-cayman
hed_page: http://hedtags.org

